import { GuestLanguage } from '../tenant-stays/stays.constants';
import { RequestOptionType } from './requests.constants';

/**
 * Epic 15, Story 15.1 AC1 — the platform-shipped request catalog, fully
 * translated in all 7 guest languages. This file is the single source of
 * truth; `seedRequestCatalog` upserts it by key, so translation fixes here
 * propagate to every hotel on the next seed run (recorded spec-note-1
 * choice: shared rows, not per-hotel copies).
 *
 * Icons are lucide names; both frontends map unknown names to a fallback.
 */
export interface DefaultRequestItem {
  key: string;
  icon: string;
  names: Record<GuestLanguage, string>;
  descriptions: Record<GuestLanguage, string>;
  optionType?: RequestOptionType;
  optionMin?: number;
  optionMax?: number;
  defaultSlaMinutes: number;
}

export interface DefaultRequestCategory {
  key: string;
  icon: string;
  names: Record<GuestLanguage, string>;
  items: DefaultRequestItem[];
}

export const DEFAULT_REQUEST_CATALOG: DefaultRequestCategory[] = [
  {
    key: 'housekeeping',
    icon: 'sparkles',
    names: {
      ar: 'التدبير الفندقي',
      en: 'Housekeeping',
      ru: 'Уборка',
      fr: 'Ménage',
      it: 'Pulizie',
      es: 'Limpieza',
      de: 'Housekeeping',
    },
    items: [
      {
        key: 'room_cleaning',
        icon: 'sparkles',
        defaultSlaMinutes: 45,
        names: {
          ar: 'تنظيف الغرفة',
          en: 'Room cleaning',
          ru: 'Уборка номера',
          fr: 'Nettoyage de la chambre',
          it: 'Pulizia della camera',
          es: 'Limpieza de la habitación',
          de: 'Zimmerreinigung',
        },
        descriptions: {
          ar: 'طلب تنظيف غرفتك',
          en: 'Have your room cleaned',
          ru: 'Уберём ваш номер',
          fr: 'Faire nettoyer votre chambre',
          it: 'Richiedi la pulizia della camera',
          es: 'Solicita la limpieza de tu habitación',
          de: 'Lassen Sie Ihr Zimmer reinigen',
        },
      },
      {
        key: 'extra_towels',
        icon: 'layers',
        defaultSlaMinutes: 20,
        optionType: 'quantity',
        optionMin: 1,
        optionMax: 4,
        names: {
          ar: 'مناشف إضافية',
          en: 'Extra towels',
          ru: 'Дополнительные полотенца',
          fr: 'Serviettes supplémentaires',
          it: 'Asciugamani extra',
          es: 'Toallas adicionales',
          de: 'Zusätzliche Handtücher',
        },
        descriptions: {
          ar: 'مناشف نظيفة إلى غرفتك',
          en: 'Fresh towels brought to your room',
          ru: 'Свежие полотенца в ваш номер',
          fr: 'Des serviettes propres livrées dans votre chambre',
          it: 'Asciugamani puliti in camera',
          es: 'Toallas limpias a tu habitación',
          de: 'Frische Handtücher aufs Zimmer',
        },
      },
      {
        key: 'bed_linens_change',
        icon: 'bed-double',
        defaultSlaMinutes: 45,
        names: {
          ar: 'تغيير أغطية السرير',
          en: 'Bed linens change',
          ru: 'Смена постельного белья',
          fr: 'Changement des draps',
          it: 'Cambio biancheria da letto',
          es: 'Cambio de sábanas',
          de: 'Bettwäschewechsel',
        },
        descriptions: {
          ar: 'أغطية سرير نظيفة',
          en: 'Fresh bed linens',
          ru: 'Свежее постельное бельё',
          fr: 'Draps propres',
          it: 'Biancheria da letto pulita',
          es: 'Sábanas limpias',
          de: 'Frische Bettwäsche',
        },
      },
      {
        key: 'pillows_blanket',
        icon: 'cloud',
        defaultSlaMinutes: 30,
        optionType: 'quantity',
        optionMin: 1,
        optionMax: 2,
        names: {
          ar: 'وسائد وبطانية',
          en: 'Pillows & blanket',
          ru: 'Подушки и одеяло',
          fr: 'Oreillers et couverture',
          it: 'Cuscini e coperta',
          es: 'Almohadas y manta',
          de: 'Kissen & Decke',
        },
        descriptions: {
          ar: 'وسائد إضافية أو بطانية',
          en: 'Extra pillows or a blanket',
          ru: 'Дополнительные подушки или одеяло',
          fr: 'Oreillers supplémentaires ou une couverture',
          it: 'Cuscini extra o una coperta',
          es: 'Almohadas extra o una manta',
          de: 'Zusätzliche Kissen oder eine Decke',
        },
      },
      {
        key: 'toiletries',
        icon: 'droplets',
        defaultSlaMinutes: 20,
        names: {
          ar: 'مستلزمات الحمام',
          en: 'Toiletries',
          ru: 'Туалетные принадлежности',
          fr: 'Articles de toilette',
          it: 'Prodotti da bagno',
          es: 'Artículos de aseo',
          de: 'Pflegeartikel',
        },
        descriptions: {
          ar: 'صابون وشامبو ومستلزمات الحمام',
          en: 'Soap, shampoo and bathroom supplies',
          ru: 'Мыло, шампунь и принадлежности для ванной',
          fr: 'Savon, shampoing et fournitures de salle de bain',
          it: 'Sapone, shampoo e prodotti per il bagno',
          es: 'Jabón, champú y artículos de baño',
          de: 'Seife, Shampoo und Badezimmerbedarf',
        },
      },
    ],
  },
  {
    key: 'maintenance',
    icon: 'wrench',
    names: {
      ar: 'الصيانة',
      en: 'Maintenance',
      ru: 'Ремонт',
      fr: 'Maintenance',
      it: 'Manutenzione',
      es: 'Mantenimiento',
      de: 'Technik',
    },
    items: [
      {
        key: 'ac_issue',
        icon: 'thermometer',
        defaultSlaMinutes: 40,
        names: {
          ar: 'مشكلة في التكييف',
          en: 'Air conditioning issue',
          ru: 'Проблема с кондиционером',
          fr: 'Problème de climatisation',
          it: "Problema con l'aria condizionata",
          es: 'Problema con el aire acondicionado',
          de: 'Problem mit der Klimaanlage',
        },
        descriptions: {
          ar: 'التكييف لا يبرّد أو لا يعمل',
          en: 'AC not cooling or not working',
          ru: 'Кондиционер не охлаждает или не работает',
          fr: 'La climatisation ne refroidit pas ou ne fonctionne pas',
          it: "L'aria condizionata non raffredda o non funziona",
          es: 'El aire no enfría o no funciona',
          de: 'Klimaanlage kühlt nicht oder funktioniert nicht',
        },
      },
      {
        key: 'plumbing_issue',
        icon: 'droplet',
        defaultSlaMinutes: 40,
        names: {
          ar: 'مشكلة في السباكة',
          en: 'Plumbing issue',
          ru: 'Проблема с сантехникой',
          fr: 'Problème de plomberie',
          it: 'Problema idraulico',
          es: 'Problema de fontanería',
          de: 'Sanitärproblem',
        },
        descriptions: {
          ar: 'تسريب أو انسداد أو مشاكل مياه',
          en: 'Leaks, drains or water problems',
          ru: 'Протечки, засоры или проблемы с водой',
          fr: "Fuites, canalisations ou problèmes d'eau",
          it: "Perdite, scarichi o problemi d'acqua",
          es: 'Fugas, desagües o problemas de agua',
          de: 'Undichtigkeiten, Abflüsse oder Wasserprobleme',
        },
      },
      {
        key: 'tv_electronics_issue',
        icon: 'tv',
        defaultSlaMinutes: 45,
        names: {
          ar: 'مشكلة في التلفاز أو الأجهزة',
          en: 'TV / electronics issue',
          ru: 'Проблема с ТВ или электроникой',
          fr: 'Problème TV / électronique',
          it: 'Problema TV / elettronica',
          es: 'Problema de TV / electrónica',
          de: 'Problem mit TV / Elektronik',
        },
        descriptions: {
          ar: 'التلفاز أو جهاز التحكم لا يعمل',
          en: 'TV, remote or device not working',
          ru: 'Телевизор, пульт или устройство не работает',
          fr: 'TV, télécommande ou appareil en panne',
          it: 'TV, telecomando o dispositivo non funzionante',
          es: 'TV, mando o dispositivo sin funcionar',
          de: 'TV, Fernbedienung oder Gerät funktioniert nicht',
        },
      },
      {
        key: 'light_electrical_issue',
        icon: 'lightbulb',
        defaultSlaMinutes: 40,
        names: {
          ar: 'مشكلة في الإضاءة أو الكهرباء',
          en: 'Light / electrical issue',
          ru: 'Проблема с освещением или электрикой',
          fr: "Problème d'éclairage / électricité",
          it: 'Problema di luci / elettricità',
          es: 'Problema de luz / electricidad',
          de: 'Licht- / Elektrikproblem',
        },
        descriptions: {
          ar: 'مشاكل الإضاءة أو المقابس أو الكهرباء',
          en: 'Lights, sockets or power problems',
          ru: 'Проблемы со светом, розетками или питанием',
          fr: 'Problèmes de lumières, prises ou courant',
          it: 'Problemi di luci, prese o corrente',
          es: 'Problemas de luces, enchufes o corriente',
          de: 'Probleme mit Licht, Steckdosen oder Strom',
        },
      },
    ],
  },
  {
    key: 'amenities',
    icon: 'package',
    names: {
      ar: 'مستلزمات إضافية',
      en: 'Amenities',
      ru: 'Удобства',
      fr: 'Équipements',
      it: 'Comfort',
      es: 'Comodidades',
      de: 'Extras',
    },
    items: [
      {
        key: 'iron_board',
        icon: 'shirt',
        defaultSlaMinutes: 25,
        names: {
          ar: 'مكواة وطاولة كي',
          en: 'Iron & ironing board',
          ru: 'Утюг и гладильная доска',
          fr: 'Fer et planche à repasser',
          it: 'Ferro e asse da stiro',
          es: 'Plancha y tabla de planchar',
          de: 'Bügeleisen & Bügelbrett',
        },
        descriptions: {
          ar: 'توصيل إلى غرفتك',
          en: 'Delivered to your room',
          ru: 'Доставим в ваш номер',
          fr: 'Livrés dans votre chambre',
          it: 'Consegnati in camera',
          es: 'Entregados en tu habitación',
          de: 'Aufs Zimmer gebracht',
        },
      },
      {
        key: 'baby_cot',
        icon: 'baby',
        defaultSlaMinutes: 45,
        names: {
          ar: 'سرير أطفال',
          en: 'Baby cot',
          ru: 'Детская кроватка',
          fr: 'Lit bébé',
          it: 'Culla',
          es: 'Cuna',
          de: 'Babybett',
        },
        descriptions: {
          ar: 'سرير أطفال يُجهَّز في غرفتك',
          en: 'A cot set up in your room',
          ru: 'Кроватку установят в вашем номере',
          fr: 'Un lit bébé installé dans votre chambre',
          it: 'Una culla montata in camera',
          es: 'Una cuna instalada en tu habitación',
          de: 'Ein Babybett wird im Zimmer aufgestellt',
        },
      },
      {
        key: 'adapter',
        icon: 'plug',
        defaultSlaMinutes: 20,
        names: {
          ar: 'محوّل كهرباء',
          en: 'Power adapter',
          ru: 'Переходник для розетки',
          fr: 'Adaptateur secteur',
          it: 'Adattatore di corrente',
          es: 'Adaptador de corriente',
          de: 'Steckdosenadapter',
        },
        descriptions: {
          ar: 'محوّل قابس لأجهزتك',
          en: 'A plug adapter for your devices',
          ru: 'Переходник для ваших устройств',
          fr: 'Un adaptateur pour vos appareils',
          it: 'Un adattatore per i tuoi dispositivi',
          es: 'Un adaptador para tus dispositivos',
          de: 'Ein Adapter für Ihre Geräte',
        },
      },
      {
        key: 'extra_hangers',
        icon: 'shirt',
        defaultSlaMinutes: 20,
        optionType: 'quantity',
        optionMin: 1,
        optionMax: 6,
        names: {
          ar: 'علّاقات ملابس إضافية',
          en: 'Extra hangers',
          ru: 'Дополнительные вешалки',
          fr: 'Cintres supplémentaires',
          it: 'Grucce extra',
          es: 'Perchas adicionales',
          de: 'Zusätzliche Kleiderbügel',
        },
        descriptions: {
          ar: 'علّاقات إضافية لخزانة الملابس',
          en: 'More hangers for the wardrobe',
          ru: 'Ещё вешалки для шкафа',
          fr: "Plus de cintres pour l'armoire",
          it: "Altre grucce per l'armadio",
          es: 'Más perchas para el armario',
          de: 'Mehr Bügel für den Schrank',
        },
      },
    ],
  },
  {
    key: 'front_desk',
    icon: 'bell',
    names: {
      ar: 'الاستقبال',
      en: 'Front Desk',
      ru: 'Ресепшен',
      fr: 'Réception',
      it: 'Reception',
      es: 'Recepción',
      de: 'Rezeption',
    },
    items: [
      {
        key: 'wake_up_call',
        icon: 'alarm-clock',
        defaultSlaMinutes: 15,
        optionType: 'time',
        names: {
          ar: 'مكالمة إيقاظ',
          en: 'Wake-up call',
          ru: 'Звонок-будильник',
          fr: 'Réveil téléphonique',
          it: 'Sveglia telefonica',
          es: 'Llamada despertador',
          de: 'Weckruf',
        },
        descriptions: {
          ar: 'اختر وقت الإيقاظ',
          en: 'Choose the time you want to be woken',
          ru: 'Выберите время звонка',
          fr: "Choisissez l'heure du réveil",
          it: "Scegli l'orario della sveglia",
          es: 'Elige la hora del despertar',
          de: 'Wählen Sie Ihre Weckzeit',
        },
      },
      {
        key: 'luggage_help',
        icon: 'luggage',
        defaultSlaMinutes: 15,
        names: {
          ar: 'مساعدة في الأمتعة',
          en: 'Luggage help',
          ru: 'Помощь с багажом',
          fr: 'Aide bagages',
          it: 'Aiuto con i bagagli',
          es: 'Ayuda con el equipaje',
          de: 'Gepäckhilfe',
        },
        descriptions: {
          ar: 'مساعدة في حمل أمتعتك',
          en: 'Help carrying your luggage',
          ru: 'Поможем донести багаж',
          fr: 'Aide pour porter vos bagages',
          it: 'Aiuto per portare i bagagli',
          es: 'Ayuda para llevar tu equipaje',
          de: 'Hilfe beim Tragen Ihres Gepäcks',
        },
      },
      {
        key: 'late_checkout_inquiry',
        icon: 'hourglass',
        defaultSlaMinutes: 30,
        names: {
          ar: 'تأخير موعد المغادرة',
          en: 'Late checkout',
          ru: 'Поздний выезд',
          fr: 'Départ tardif',
          it: 'Check-out posticipato',
          es: 'Salida tardía',
          de: 'Später Check-out',
        },
        descriptions: {
          ar: 'استفسر عن تمديد وقت المغادرة',
          en: 'Ask about extending your checkout time',
          ru: 'Узнайте о продлении времени выезда',
          fr: 'Demandez une prolongation de votre départ',
          it: 'Chiedi di prorogare il check-out',
          es: 'Pregunta por ampliar tu hora de salida',
          de: 'Fragen Sie nach einem späteren Check-out',
        },
      },
    ],
  },
];
